### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by hya1711** [MolecularMatters/psd_sdk#11]
NativeFile can support android ？

**Comment by MolecularMatters** [comment]
The Android NDK should give you access to most Unix functions, so we don't see any reason why it shouldn't work on Android. It's probably best to start by taking the Linux implementation and work from there.

**Comment by hya1711** [comment]
> The Android NDK should give you access to most Unix functions, so we don't see any reason why it shouldn't work on Android. It's probably best to start by taking the Linux implementation and work from there.

The android studio compilation prompts that the aio.h file is missing, which has been resolved after downloading the aio source code.
