### ISSUE TITLE
Can this library be called from node js?

### ISSUE THREAD

**Issue by velara3** [MolecularMatters/psd_sdk#12]
I'm currently on Mac and would like to parse PSD into a JSON string and export the layers to PNGs from a server. I'm currently using node js and exppressjs. I'm used to using npm to load libraries but unfamiliar with loading a C++ library. Is there any documentation on how to use it in node js? Would I call it as a process? Is it command line? Any help would be appreciated. 

I have VSCode and Visual Studio Mac edition but haven't used VS much for many years.

**Comment by MolecularMatters** [comment]
This SDK is a C++ library, intended to be used in native applications.
There might be a way to use this in nodejs as well, but you'd have to consult Google for that.
