### ISSUE TITLE
Cannot be successfully used after compiling to lib

### ISSUE THREAD

**Issue by SkyD666** [MolecularMatters/psd_sdk#14]
![自由截图 - 2022-12-19_211803_990403](https://user-images.githubusercontent.com/32453770/208434763-da2ecb2e-9685-4182-b1fe-11bc1a382c34.png)

.lib zip file:
[psd_sdk.zip](https://github.com/MolecularMatters/psd_sdk/files/10259518/psd_sdk.zip)

**Comment by MolecularMatters** [comment]
What you're describing has nothing to do with the library.

Your IDE warns that certain headers are not used. Either disable this warning (which I would not recommend), or remove the includes so the IDE doesn't trigger these warnings.

**Comment by SkyD666** [comment]
Please see the compile error message below the image
thanks

**Comment by tivolo** [comment]
This is not a compiler error, but a linker error.
The linker cannot find the symbol for the destructor of Allocator, which is defined in PsdAllocator.cpp.

Either you forgot to add this to the static library, or you don't link against the static library correctly.

In either case, the SDK definitely does build out of the box. Whether you compile .cpps into .objs on their own, or put them into a static library doesn't make a difference. You need to make sure the setup on your end is correct.

**Comment by MolecularMatters** [comment]
Closing this issue now since it doesn't have to do with the library itself.
