### ISSUE TITLE
Is resizing of Layers possible?

### ISSUE THREAD

**Issue by 2shady4u** [MolecularMatters/psd_sdk#2]
Hello!
First off, thanks for maintaining this repository :)
I'm making good use of it in my [Godot Plugin](https://github.com/2shady4u/godot-psd-importer).

**My issue/feature request:**
Is it possible to rescale/resize a PsdLayer? 
I didn't really find any possible way to do this and it would help immensely for my project.
I know there's a thumbnail, but I don't know if abusing thumbnails is the 
recommended way to do this.

Cheers!

**Comment by MolecularMatters** [comment]
Rescaling or resizing layers is not a feature I would put into the SDK directly, especially with the number of resizing filters (linear, cubic, etc.) you'd have to implement.

As soon as you read the layer data, you end up with RGB or RGBA data anyway. You can then consume this data in any way you see fit, and use (existing) code or probably other libraries for resizing content.

**Comment by 2shady4u** [comment]
Okay, I'll use ImageMagick then as my resizer (had to implement it anyway for PNG export)

Unrelated, but are you perhaps, in the future, interested in supporting KRA and/or ORA formats? (Krita's Image Documents)

**Comment by MolecularMatters** [comment]
Not for this library, no. I want this library to focus on PSD only.
