### ISSUE TITLE
Layered Output files

### ISSUE THREAD

**Issue by EmilDohne** [MolecularMatters/psd_sdk#24]
I had a read through the source code and the samples, and unless I am mistaken, it is currently not possible to create a layer structure like the one described below as a psd export correct?

```
GroupLayer
   |_ ImageLayer
   |_ GroupLayer
      |_ ...
...
```

**Comment by MolecularMatters** [comment]
You are correct.
The library was initially only supposed to be reading PSD files, and exporting was added at a later point.

It would have to be restructured significantly to make exporting PSDs support more features.

**Comment by EmilDohne** [comment]
No worries, since I need it for a project of mine I might give it a go and see if I can implement it. No promises but if I have something I'll create a PR

**Comment by EmilDohne** [comment]
Hey, I just wanted to give an update to this since I initially got started trying to implement this for the psd_sdk but realized, as you mentioned, that it would require a fairly major restructure. Since I still needed these features I actually spent the time since then working on my [own library](https://github.com/EmilDohne/PhotoshopAPI) for doing this.

**Comment by MolecularMatters** [comment]
Thanks for the update and good luck with your library!

I'll close this for now.

**Comment by EmilDohne** [comment]
Thank you!
