### ISSUE TITLE
Copiling Samples fails

### ISSUE THREAD

**Issue by ademmler** [MolecularMatters/psd_sdk#26]
When I try to compile the samples I get:
psd_sdk/src/Samples/PsdDebug.h:8:11 Use of undeclared identifier 'stderr'
When I add "#include stdio" I get a duplicate symbols error.

How to overcome this?

**Comment by tivolo** [comment]
Which platform are you compiling for?
And what is the exact duplicate symbols error?

**Comment by ademmler** [comment]
Sorry I forgot to add this:

Mac OS X Ventura 13.4 / Xcode 14.3.1

```
duplicate symbol 'OutputDebugStringA(char const*)' in:
    psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Intermediates.noindex/psd_sdk.build/Debug/PsdSamples.build/Objects-normal/x86_64/PsdSamples.o
    psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Intermediates.noindex/psd_sdk.build/Debug/PsdSamples.build/Objects-normal/x86_64/PsdTgaExporter.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Here is the long response:
`Ld /Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Products/Debug/PsdSamples normal (in target 'PsdSamples' from project 'psd_sdk')
    cd /Users/username/SDKs/psd_sdk/build/Xcode
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -Xlinker -reproducible -target x86_64-apple-macos10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -L/Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Intermediates.noindex/EagerLinkingTBDs/Debug -L/Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Products/Debug -F/Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Intermediates.noindex/EagerLinkingTBDs/Debug -F/Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Products/Debug -filelist /Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Intermediates.noindex/psd_sdk.build/Debug/PsdSamples.build/Objects-normal/x86_64/PsdSamples.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Intermediates.noindex/psd_sdk.build/Debug/PsdSamples.build/Objects-normal/x86_64/PsdSamples_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -stdlib\=libc++ -framework Foundation -framework CoreFoundation -lpsd_sdk -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Intermediates.noindex/psd_sdk.build/Debug/PsdSamples.build/Objects-normal/x86_64/PsdSamples_dependency_info.dat -o /Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Products/Debug/PsdSamples
`

**Comment by MolecularMatters** [comment]
The #defines in PsdDebug.h didn't make any sense for Apple platforms, since they introduced the definition of OutputDebugStringA directly in the header. The header was pulled in from both PsdSamples.cpp as well as PsdTgaExporter.cpp, naturally leading to multiple defined symbols.

This should be fixed in https://github.com/MolecularMatters/psd_sdk/commit/311b5c2e3fe04c8cc6a563665e66b19b3fcf8116.

**Comment by ademmler** [comment]
Super - thx for fixing this.

I have updated my src to your suggestion. But now I get:
Undefined symbol: OutputDebugStringA(char const*)


```
Ld /Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Products/Debug/PsdSamples normal (in target 'PsdSamples' from project 'psd_sdk')
    cd /Users/username/SDKs/psd_sdk/build/Xcode
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -Xlinker -reproducible -target x86_64-apple-macos10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -L/Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Intermediates.noindex/EagerLinkingTBDs/Debug -L/Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Products/Debug -F/Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Intermediates.noindex/EagerLinkingTBDs/Debug -F/Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Products/Debug -filelist /Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Intermediates.noindex/psd_sdk.build/Debug/PsdSamples.build/Objects-normal/x86_64/PsdSamples.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Intermediates.noindex/psd_sdk.build/Debug/PsdSamples.build/Objects-normal/x86_64/PsdSamples_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -stdlib\=libc++ -framework Foundation -framework CoreFoundation -lpsd_sdk -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Intermediates.noindex/psd_sdk.build/Debug/PsdSamples.build/Objects-normal/x86_64/PsdSamples_dependency_info.dat -o /Users/username/SDKs/psd_sdk/build/Xcode/DerivedData/psd_sdk/Build/Products/Debug/PsdSamples

Undefined symbols for architecture x86_64:
  "OutputDebugStringA(char const*)", referenced from:
      SampleReadPsd() in PsdSamples.o
      SampleWritePsd() in PsdSamples.o
      tgaExporter::CreateFile(wchar_t const*) in PsdTgaExporter.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
